### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by jletey** [unifiedjs/design-system#16]
### Subject of the feature

Just stumbled upon this repo, and I think that having one design system throughout the collective is a brilliant idea. It got me thinking that maybe the collective should have a **design** team (like the **core** and **moderation** teams). Let me know if this is something worth discussing!

I'm not entirely quite sure how many repositories across the collective actually use this project, or what you guys have in mind for the future of this repo - but I do have a few ideas:

- Transfer to [Theme UI](https://theme-ui.com)
   - Since this project was created pre Theme UI era, I think it would be worthwhile transferring everything over from `styled-components` and `styled-system`.
- [`unified-ui.now.sh`](https://unified-ui.now.sh) -> [`unifiedjs.com/design`](https://unifiedjs.com/design)
   - Like [`zeit.co/design`](https://zeit.co/design).
- Switch over to Gatsby
   - Although [x0](https://github.com/c8r/x0) is a great tool - if this is going to be expanded to a complete design system, it will be limiting.
   - Match styles of the new [`unifiedjs.com`](https://unifiedjs.com) site.

### Problem

N/A

### Expected behaviour

N/A

### Alternatives

Leaving the code/repo as-is 😅

**Comment by wooorm** [comment]
We could use some design help!

> design team

Sure, but currently no-one is working on it; our teams are setup to have specific permissions and rights, so it seems a bit much to spin up a team now. But I don’t think that prevents anyone from working on things!

> how many repositories across the collective actually use this project

Currently, none. This repo was created to set up a single style for the websites of our big projects (mdx, remark, rehype, retext, vfile, syntax-tree, unified, etc), but work stalled.
That’s still a good idea, but in the meantime I created the current version of the unified website.

**Comment by jletey** [comment]
> so it seems a bit much to spin up a team now

Understand, was just a thought

> but work stalled

I would love to pick up the torch where John left off a few years back. Although the collective is a group of **federated** projects, I definitely think that having some connection design wise would be good. I see that the mdx project is looking for a redesign of their website (https://github.com/mdx-js/mdx/issues/444), I think this would be a perfect opportunity to start using the unified design system 😄

> I created the current version of the unified website.

I'm a huge fan of the most recent version of the unified website, and we should probably port over some styles 👍

**Comment by wooorm** [comment]
Closing these issues as the repo was archived now. Then archiving the repo again!
